#!/usr/bin/env python

env = SConscript("../godot-cpp/SConstruct")
env.Append(CPPPATH='src')

sources = Glob('src/*.cpp')
library = env.SharedLibrary("../game/bin/libgame{}{}".format(env["suffix"], env["SHLIBSUFFIX"]), source=sources)

Default(library)